"""Guard .agent/rules/README.md against rotting into dead links again (#7990).

The index used to be generated by the retired agentsync tool; by 2026-10 about
55 of its ~60 links pointed at files that no longer existed. It is now
maintained by hand, so these tests hold it to the directory's real contents.
"""

import re
from pathlib import Path

RULES_DIR = Path(__file__).parent.parent / ".agent" / "rules"
INDEX = RULES_DIR / "README.md"
LINK = re.compile(r"\]\(([^)\s]+)\)")


def _local_targets(text: str) -> list[str]:
    targets = []
    for target in LINK.findall(text):
        if re.match(r"[a-z][a-z0-9+.-]*:", target, re.I):  # http:, mailto:, ...
            continue
        path = target.split("#", 1)[0]
        if path:
            targets.append(path)
    return targets


def test_every_index_link_resolves() -> None:
    targets = _local_targets(INDEX.read_text())
    assert targets, "index lists no documents"
    dead = [t for t in targets if not (RULES_DIR / t).is_file()]
    assert dead == [], f"dead links in {INDEX.name}: {dead}"


def test_every_rules_document_is_indexed() -> None:
    linked = {(RULES_DIR / t).resolve() for t in _local_targets(INDEX.read_text())}
    unlisted = sorted(
        p.relative_to(RULES_DIR).as_posix() for p in RULES_DIR.rglob("*.md")
        if p != INDEX and p.resolve() not in linked
    )
    assert unlisted == [], f"documents missing from {INDEX.name}: {unlisted}"
