"""Agent config health checks for scanner and dashboard surfacing."""

import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

AGENT_CONFIG_FILES = ("CLAUDE.md", "AGENTS.md")
RULES_DIRS = ((".agentsync", "rules"), (".agent", "rules"))
MAX_LINES = 200
STALENESS_DAYS = 30


def build_empty_agent_config_health(project_name: str = "") -> Dict[str, Any]:
    return {
        "project": project_name,
        "files": [
            {"path": "CLAUDE.md", "exists": False, "line_count": 0, "over_limit": False, "prose_ratio": 0.0, "boilerplate_ratio": 0.0, "stale": False, "last_modified": None, "warnings": []},
            {"path": "AGENTS.md", "exists": False, "line_count": 0, "over_limit": False, "prose_ratio": 0.0, "boilerplate_ratio": 0.0, "stale": False, "last_modified": None, "warnings": []},
        ],
        "warning_count": 0,
        "has_claude_md": False,
        "has_agents_md": False,
        "has_agent_rules": False,
    }


def _count_lines(content: str) -> int:
    return content.count("\n") + (1 if content and not content.endswith("\n") else 0)


def _prose_ratio(content: str) -> float:
    lines = content.splitlines()
    if not lines:
        return 0.0

    prose_lines = 0
    in_code_block = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code_block = not in_code_block
            continue
        if in_code_block or not stripped:
            continue
        if re.match(r"^(#{1,6}\s|[-*]\s|[0-9]+\.\s|\|.*\||>|<!--)", stripped):
            continue
        if len(stripped) < 40:
            continue
        prose_lines += 1

    non_empty = sum(1 for line in lines if line.strip())
    return round(prose_lines / non_empty, 2) if non_empty else 0.0


def _boilerplate_ratio(content: str) -> float:
    lines = content.splitlines()
    if not lines:
        return 0.0

    boilerplate_lines = 0
    in_managed = False
    for line in lines:
        stripped = line.strip()
        if any(marker in stripped for marker in ("AGENTSYNC:START", "SCAFFOLD:START", "MANIFEST:AUTO:START")):
            in_managed = True
            boilerplate_lines += 1
            continue
        if any(marker in stripped for marker in ("AGENTSYNC:END", "SCAFFOLD:END", "MANIFEST:AUTO:END")):
            in_managed = False
            boilerplate_lines += 1
            continue
        if in_managed:
            boilerplate_lines += 1
        elif any(marker in stripped for marker in ("This file is managed by", "Auto-generated by", "Do not edit between markers", "Do not edit this section")):
            boilerplate_lines += 1

    return round(boilerplate_lines / len(lines), 2)


def _file_last_modified(filepath: Path) -> Optional[str]:
    try:
        return datetime.fromtimestamp(filepath.stat().st_mtime, tz=timezone.utc).strftime("%Y-%m-%d")
    except OSError:
        return None


def _last_commit_date(project_dir: Path) -> Optional[datetime]:
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%aI"],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0 and result.stdout.strip():
            return datetime.fromisoformat(result.stdout.strip())
    except (subprocess.TimeoutExpired, OSError, ValueError):
        pass
    return None


def _is_stale(filepath: Path, project_dir: Path) -> bool:
    try:
        file_mtime = datetime.fromtimestamp(filepath.stat().st_mtime, tz=timezone.utc)
    except OSError:
        return False

    last_commit = _last_commit_date(project_dir)
    if last_commit is None:
        return False
    if last_commit.tzinfo is None:
        last_commit = last_commit.replace(tzinfo=timezone.utc)

    now = datetime.now(tz=timezone.utc)
    return (now - last_commit).days < STALENESS_DAYS and (now - file_mtime).days > STALENESS_DAYS


def _check_file(filepath: Path, project_dir: Path) -> Dict[str, Any]:
    rel_path = filepath.name if filepath.parent == project_dir else str(filepath.relative_to(project_dir))
    health = {
        "path": rel_path,
        "exists": filepath.exists(),
        "line_count": 0,
        "over_limit": False,
        "prose_ratio": 0.0,
        "boilerplate_ratio": 0.0,
        "stale": False,
        "last_modified": None,
        "warnings": [],
    }
    if not filepath.exists():
        return health

    content = filepath.read_text(errors="replace")
    health["line_count"] = _count_lines(content)
    health["over_limit"] = health["line_count"] > MAX_LINES
    health["prose_ratio"] = _prose_ratio(content)
    health["boilerplate_ratio"] = _boilerplate_ratio(content)
    health["stale"] = _is_stale(filepath, project_dir)
    health["last_modified"] = _file_last_modified(filepath)

    if health["over_limit"]:
        health["warnings"].append(f"{health['line_count']} lines (limit: {MAX_LINES})")
    if health["prose_ratio"] > 0.4:
        health["warnings"].append(
            f"High prose ratio ({health['prose_ratio']:.0%}) — consider atomic one-concept-per-line rules"
        )
    if health["stale"]:
        health["warnings"].append(
            f"Stale — last modified {health['last_modified']}, project has recent commits"
        )
    return health


def get_agent_config_health(project_dir: Path) -> Dict[str, Any]:
    health = build_empty_agent_config_health(project_dir.name)
    health["files"] = [_check_file(project_dir / filename, project_dir) for filename in AGENT_CONFIG_FILES]
    health["has_claude_md"] = (project_dir / "CLAUDE.md").exists()
    health["has_agents_md"] = (project_dir / "AGENTS.md").exists()

    for rules_root in RULES_DIRS:
        rules_dir = project_dir.joinpath(*rules_root)
        if not rules_dir.is_dir():
            continue
        health["has_agent_rules"] = True
        for md_file in sorted(rules_dir.glob("*.md")):
            health["files"].append(_check_file(md_file, project_dir))

    health["warning_count"] = sum(len(file_health["warnings"]) for file_health in health["files"])
    return health